apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/postgresql.cnpg.io_backups.yaml
  - upstream/postgresql.cnpg.io_clusterimagecatalogs.yaml
  - upstream/postgresql.cnpg.io_clusters.yaml
  - upstream/postgresql.cnpg.io_databases.yaml
  - upstream/postgresql.cnpg.io_failoverquorums.yaml
  - upstream/postgresql.cnpg.io_imagecatalogs.yaml
  - upstream/postgresql.cnpg.io_poolers.yaml
  - upstream/postgresql.cnpg.io_publications.yaml
  - upstream/postgresql.cnpg.io_scheduledbackups.yaml
  - upstream/postgresql.cnpg.io_subscriptions.yaml
