apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/upstream/cert-manager.crds.yaml
  - cloudnative-pg
  - gateway-api/upstream
  - prometheus-operator/helmrepository.yaml
  - prometheus-operator/helmrelease.yaml
  - temporal-worker-controller/helmrepository.yaml
  - temporal-worker-controller/helmrelease.yaml
